// src/lib/components/terminal.svelte
<script lang="ts">
    import { ping, pong } from "$lib/scripts/commands/system";
    import { theme } from "$lib/scripts/commands/theme";
    import {
        commandHandler,
        commandHistory,
        getActivePrefix,
        loadCommands,
        parseCommandOutput,
    } from "$lib/scripts/terminal.svelte";
    import { onMount } from "svelte";

    loadCommands([pong, ping, theme]);

    let input = $state<HTMLInputElement | null>(null);
    let focused = $state(false);

    const focusInput = () => {
        if (input) {
            input.focus();
            input.select();
        }
    };

    export const stop = (event: Event) => {
        event.stopPropagation();
    };

    onMount(() => {
        if (input) {
            input.addEventListener("focus", () => {
                focused = true;
            });
            // unfocuse event handler got annoying, so commented out
            // input.addEventListener("blur", () => {
            //     focused = false;
            // });
        }
    });
</script>

<div class="terminal-container">
    <div
        class="terminal"
        class:focused
        tabindex="0"
        role="button"
        onclick={focusInput}
        onkeydown={() => {}}
    >
        <div class="command-output" class:focused>
            {#each commandHistory as command}
                <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
                <p onclick={stop}>{@html parseCommandOutput(command)}</p>
            {/each}
        </div>
        <form class="command-input">
            {@html getActivePrefix(true) + "&nbsp;"}
            <input
                bind:this={input}
                type="text"
                onkeydown={commandHandler}
                autocapitalize="off"
                autocomplete="off"
                autocorrect="off"
            />
        </form>
    </div>
</div>

<style lang="scss">
    @use "$lib/scss/var";
    @use "$lib/scss/mixins";

    :global(.primary, .secondary) {
        font-family: monospace;
        font-size: 16px;
    }

    :global(.primary) {
        color: var.$primary;
    }

    :global(.secondary) {
        color: var.$primary-a;
    }

    .terminal-container {
        height: 0px; // Without a height, the flex container will not expand
        flex: auto;
        padding-bottom: var.$gap;

        // .terminal .focused {
        //     // background-color: blue !important;
        //     height: fit-content;
        // }

        .terminal {
            margin: var.$gap;
            padding: 4px var.$gap 0 var.$gap;
            border-radius: 8px;
            background-color: var.$primary-a;

            height: fit-content;
            font-family: monospace;
            display: flex;
            flex-direction: column;
            transition: all 0.3s ease-out;

            &.focused {
                height: 100%;
            }

            * {
                font-size: 16px;
            }

            .command-output {
                transition: all 0.3s ease-out;
                flex: none;
                height: 0px;
                overflow-y: auto;

                &::-webkit-scrollbar {
                    display: none;
                }

                &.focused {
                    flex: 1;
                }
            }

            .command-input {
                height: 30px;
                width: 100%;
                display: flex;
                flex-direction: row;

                input {
                    width: 0;
                    flex: 1;
                    background-color: transparent;
                    border: none;
                    // border: 2px solid red;
                    font-family: monospace;
                    outline: none;
                    margin: 0 0 6px -4px;

                    &::placeholder {
                        color: var.$text;
                        opacity: 0.5;
                    }
                }
            }
        }
    }
</style>

// src/components/Terminal.vue
<script setup lang="ts">
import { adviceCommand } from "../scripts/commands/adviceCommand";
import {
    cdCommand,
    exitCommand,
    lsCommand,
    spotlightCommand,
    testCommand,
    themeCommand,
} from "../scripts/commands/systemCommands";
import { formatString, outputToHTML, prefixToString } from "../scripts/commands/Command";
import {
    commandInput,
    commandHandler,
    loadTerminal,
    Outputs,
    prefix,
    showTerminal,
    loadCommands,
} from "../scripts/terminal";

loadCommands([cdCommand, testCommand, adviceCommand, exitCommand, lsCommand, themeCommand, spotlightCommand]);
</script>

<template>
    <div class="div-terminal-container" v-if="showTerminal" @click="showTerminal = false">
        <div class="div-terminal-border">
            <div class="div-terminal" @click.stop="commandInput?.focus()">
                <!-- -->
                <p class="output" v-for="output in Outputs" v-html="outputToHTML(output)" @click.stop></p>
                <div class="div-input" @keydown="commandHandler">
                    <p v-html="formatString(prefixToString(prefix))"></p>
                    <input
                        autofocus
                        autocorrect="off"
                        spellcheck="false"
                        autocapitalize="off"
                        type="text"
                        ref="commandInput"
                        @focus="loadTerminal($route.fullPath)" />
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped lang="scss">
.div-terminal-container {
    background-color: rgba(0, 0, 0, 0.3);
    position: fixed;
    left: 0;
    top: 0;
    width: 100vw;
    height: 100vh;
    z-index: 5;
    backdrop-filter: blur(5px);

    p {
        font-family: ubuntu mono;
        overflow-wrap: break-word;
    }

    span {
        font-family: ubuntu mono;
    }

    .div-terminal-border {
        position: inherit;
        border: 2px var(--blue) solid;
        border-radius: 8px;
        width: 80%;
        height: 80%;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: var(--blue-background);
        padding: 10px;

        .div-terminal {
            background-color: var(--background);
            font-family: ubuntu mono;
            font-size: 20px;
            padding: 15px;
            overflow-y: scroll;
            overflow-x: hidden;
            scrollbar-width: none;
            border-radius: 8px;
            height: 100%;
            width: 100%;
            cursor: text;

            @media (max-width: 700px) {
                margin: 10px 0 0 10px;
                height: 60%;
                width: calc(100vw - 20px);
                font-size: 16px;
            }

            &::-webkit-scrollbar {
                display: none;
            }

            .output {
                width: fit-content;
            }

            .div-input {
                display: flex;
                flex-direction: row;

                @media (max-width: 700px) {
                    width: calc(100vw - 20px - 30px);
                }

                input {
                    flex: 1;
                    color: var(--text);
                    background-color: transparent;
                    font-size: 20px;
                    border: none;
                    margin-left: 9px;
                    width: 100%;
                    padding: 1px 2px;
                    border-radius: 0;

                    @media (max-width: 700px) {
                        font-size: 16px;
                    }
                }
            }
        }
    }
}
</style>
