// src/lib/components/terminal.svelte
<script lang="ts">
    let commandHistory = $state<string[]>([]);

    for (let i = 0; i < 10; i++) {
        commandHistory.push(`Command ${i + 1}`);
    }
</script>

<div class="terminal-container">
    <div class="command-output">
        {#each commandHistory as command}
            <p>{command}</p>
            <p>{command}</p>
        {/each}
    </div>
    <div class="command-input">
        <p>guest@huon.dev:~$&nbsp;</p>
        <input
            type="text"
            onclick={() => {
                commandHistory.push("toot");
            }}
        />
    </div>
</div>

<style lang="scss">
    @use "$lib/scss/var";
    @use "$lib/scss/mixins";

    .terminal-container {
        padding: 0 var.$gap;
        height: 0px; // Without a height, the flex container will not expand
        flex: auto;
        font-family: monospace;
        display: flex;
        flex-direction: column;

        * {
            font-size: 16px;
        }

        .command-output {
            flex: 1;
            overflow-y: auto;
        }

        .command-input {
            height: 30px;
            width: 100%;
            display: flex;
            flex-direction: row;

            input {
                width: 0;
                flex: 1;
                background-color: transparent;
                border: none;
                // border: 2px solid red;
                font-family: monospace;
                outline: none;
                margin: 0 0 6px 0;

                &::placeholder {
                    color: var.$text;
                    opacity: 0.5;
                }
            }
        }
    }
</style>

// client/src/components/Terminal.vue
<script setup lang="ts">
import { commandInput, commandHandler, loadTerminal, Outputs, Prefix, showTerminal } from '../scripts/terminal';
</script>

<template>
<div class="div-terminal-container" v-if="showTerminal" @click="showTerminal = false">
    <div class="div-terminal" @click="(e) => {commandInput?.focus(); e.stopPropagation()}">
        <p class="output" v-for="output in Outputs">
            <span v-if="output[0]"><span class="dark-blue" v-text="Prefix[0]"/>:<span class="blue" v-text="output[0]"/>$</span> {{ output[1] }}
        </p>
        <div class="div-input" @keydown="commandHandler">
            <p><span v-for="(term, index) in Prefix" :class="{'dark-blue': index === 0, blue: index == 2}" v-text="term"/></p>
            <input autofocus type="text" ref="commandInput" @focus="loadTerminal($route.fullPath)">
        </div>
    </div>
</div>
</template>

<style scoped lang="scss">
.blue {
    color: var(--blue-alt);
}

.dark-blue {
    color: var(--blue-border);
}

.div-terminal-container {
    background-color: rgba(0, 0, 0, 0.3);
    position: fixed;
    left: 0;
    top: 0;
    width: 100vw;
    height: 100vh;
    z-index: 5;
	backdrop-filter: blur(5px);

    p {
        font-family: ubuntu mono;
    }

    span {
        font-family: ubuntu mono;
    }

    .div-terminal {
        position: inherit;
        background-color: var(--background);
        border: 2px var(--blue-border) solid;
        border-radius: 8px;
        width: 80%;
        height: 80%;
        margin: 5% 0 0 10%;
        font-family: ubuntu mono;
        font-size: 20px;
        padding: 15px;
        overflow-y: scroll;
        scrollbar-width: none;

        &::-webkit-scrollbar {
            display: none;
        }

        .div-input {
            display: flex;
            flex-direction: row;

            input {
                flex: 1;
                color: var(--text);
                background-color: transparent;
                font-size: 20px;
                border: none;
                margin-left: 9px;
            }
        }
    }
}
</style>
